name: 'Shipa Cloud'
description: 'Manage cloud-native deployments and policies on Kubernetes using GitHub Actions and Shipa'
branding:
  icon: "upload-cloud" 
  color: "blue"
inputs:
  shipa-action:
    description: 'File path to Shipa action yml file'
    required: true
runs:
  using: 'docker'
  image: 'docker://shipasoftware/shipa-action:a3419433bc287c4572b248f5afd80a57b1f79a72'
  args:
    - --shipa-action=${{ inputs.shipa-action }}
